### ISSUE TITLE
Roadmap para refatoração

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#54]
Objetivo: permitir que o sistema possa atender a demandas de chamados de quaisquer setores da unidade.
Para isso, as alterações estão divididas el algumas tarefas:

- [x] criar estrutura de setores
- [x] renomear estrutura de categorias para filas e relacionar as filas com setores
- [x] criar interface para cadastrar filas, atendentes por fila, etc
- [x] reorganizar as migrations e seeders para a nova estrutura mantendo compatibilidade com sqlite para testes
- [x] refatorar a lista de 'meus chamados' para usar datatables
- [x] reorganizar a tela de um chamado  para conteúdo responsivo
- [x] implementar upload de arquivos
- [x] implementar detalhes de um chamado usando forms dinâmicos personalizado por fila
- [x] implementar envio de emails para todos os envolvidos em cada chamado
- [x] permitir linkar chamados entre si (chamados relacionados)
- [x] permitir atribuir um chamado a vários técnicos
- [ ] outras tarefas ???

* Essas tarefas podem ser quebradas em issues;
* Novas tarefas podem ser adicionadas conforme necessidade;
* Criar MVP para poder entrar em produção em tempo razoável;
